apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: zeblit
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zeblit
      component: backend
  template:
    metadata:
      labels:
        app: zeblit
        component: backend
    spec:
      containers:
      - name: backend
        image: zeblit/backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zeblit-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: zeblit-config
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zeblit-secrets
              key: jwt-secret
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: zeblit-config
              key: environment
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: zeblit
    component: backend
spec:
  selector:
    app: zeblit
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP 