apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: zeblit
    component: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: zeblit
      component: redis
  template:
    metadata:
      labels:
        app: zeblit
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "512mb"
        - --maxmemory-policy
        - "allkeys-lru"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: redis-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: zeblit
    component: redis
spec:
  selector:
    app: zeblit
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP 