"""fix_conversation_updated_at_onupdate

Revision ID: 3fb9c7777f23
Revises: c08bfb4d750b
Create Date: 2025-08-16 07:40:31.259093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb9c7777f23'
down_revision: Union[str, Sequence[str], None] = 'c08bfb4d750b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
