"""update_container_model_to_match_service_expectations

Revision ID: 3ff0b8424089
Revises: 7e21f445e1ed
Create Date: 2025-08-15 11:53:47.461297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff0b8424089'
down_revision: Union[str, Sequence[str], None] = '7e21f445e1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('container_name', sa.String(length=255), nullable=True))
    op.add_column('containers', sa.Column('cpu_limit', sa.Float(), nullable=False))
    op.add_column('containers', sa.Column('memory_limit', sa.Integer(), nullable=False))
    op.add_column('containers', sa.Column('disk_limit', sa.Integer(), nullable=False))
    op.add_column('containers', sa.Column('environment_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('containers', sa.Column('auto_sleep_minutes', sa.Integer(), nullable=False))
    op.add_column('containers', sa.Column('auto_stop_hours', sa.Integer(), nullable=False))
    op.add_column('containers', sa.Column('auto_delete_days', sa.Integer(), nullable=False))
    op.add_column('containers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('stopped_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'stopped_at')
    op.drop_column('containers', 'started_at')
    op.drop_column('containers', 'updated_at')
    op.drop_column('containers', 'auto_delete_days')
    op.drop_column('containers', 'auto_stop_hours')
    op.drop_column('containers', 'auto_sleep_minutes')
    op.drop_column('containers', 'environment_vars')
    op.drop_column('containers', 'disk_limit')
    op.drop_column('containers', 'memory_limit')
    op.drop_column('containers', 'cpu_limit')
    op.drop_column('containers', 'container_name')
    # ### end Alembic commands ###
