"""add_project_id_to_agents_table

Revision ID: 7e21f445e1ed
Revises: 039c22fe7375
Create Date: 2025-08-15 11:16:55.249956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e21f445e1ed'
down_revision: Union[str, Sequence[str], None] = '039c22fe7375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('project_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('agents_agent_type_key'), 'agents', type_='unique')
    op.create_foreign_key(None, 'agents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_unique_constraint(op.f('agents_agent_type_key'), 'agents', ['agent_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('agents', 'project_id')
    # ### end Alembic commands ###
