"""add_missing_container_fields_and_methods

Revision ID: 8a2ca08b32e5
Revises: 3ff0b8424089
Create Date: 2025-08-15 12:15:25.582044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2ca08b32e5'
down_revision: Union[str, Sequence[str], None] = '3ff0b8424089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('last_health_check', sa.DateTime(), nullable=True))
    op.add_column('containers', sa.Column('cpu_usage_percent', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('memory_usage_mb', sa.Integer(), nullable=True))
    op.add_column('containers', sa.Column('disk_usage_mb', sa.Integer(), nullable=True))
    op.add_column('containers', sa.Column('network_in_mb', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('network_out_mb', sa.Float(), nullable=True))
    op.add_column('containers', sa.Column('health_check_failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('containers', sa.Column('external_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'external_port')
    op.drop_column('containers', 'health_check_failures')
    op.drop_column('containers', 'network_out_mb')
    op.drop_column('containers', 'network_in_mb')
    op.drop_column('containers', 'disk_usage_mb')
    op.drop_column('containers', 'memory_usage_mb')
    op.drop_column('containers', 'cpu_usage_percent')
    op.drop_column('containers', 'last_health_check')
    op.drop_column('containers', 'last_activity_at')
    # ### end Alembic commands ###
