"""Convert resource limit columns to integers

Revision ID: bdee67ff8c4d
Revises: c82127dc0c64
Create Date: 2025-08-15 09:53:41.328922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdee67ff8c4d'
down_revision: Union[str, Sequence[str], None] = 'c82127dc0c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with proper type conversion."""
    
    # Convert string resource limit columns to integers using USING clause
    # This handles the existing string values and converts them to integers
    
    op.execute("ALTER TABLE projects ALTER COLUMN max_containers TYPE INTEGER USING max_containers::integer")
    op.execute("ALTER TABLE projects ALTER COLUMN max_storage_mb TYPE INTEGER USING max_storage_mb::integer")
    op.execute("ALTER TABLE projects ALTER COLUMN max_compute_hours TYPE INTEGER USING max_compute_hours::integer")
    op.execute("ALTER TABLE projects ALTER COLUMN current_containers TYPE INTEGER USING current_containers::integer")
    op.execute("ALTER TABLE projects ALTER COLUMN current_storage_mb TYPE INTEGER USING current_storage_mb::integer")
    op.execute("ALTER TABLE projects ALTER COLUMN current_compute_hours TYPE INTEGER USING current_compute_hours::integer")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'current_compute_hours',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'current_storage_mb',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'current_containers',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'max_compute_hours',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'max_storage_mb',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'max_containers',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
