"""add_conversation_fields_and_fix_relationships

Revision ID: c08bfb4d750b
Revises: 8a2ca08b32e5
Create Date: 2025-08-16 07:36:24.731708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c08bfb4d750b'
down_revision: Union[str, Sequence[str], None] = '8a2ca08b32e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    op.add_column('agent_messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_messages', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('agent_messages', sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'agent_messages', 'agent_messages', ['parent_message_id'], ['id'])
    op.alter_column('containers', 'health_check_failures',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('conversations', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('conversations', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.drop_column('conversations', 'user_message')
    op.drop_column('conversations', 'agent_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('agent_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'total_tokens')
    op.drop_column('conversations', 'message_count')
    op.drop_column('conversations', 'is_active')
    op.drop_column('conversations', 'context')
    op.drop_column('conversations', 'title')
    op.alter_column('containers', 'health_check_failures',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.drop_column('agent_messages', 'message_metadata')
    op.drop_column('agent_messages', 'model_used')
    op.drop_column('agent_messages', 'total_tokens')
    op.drop_column('agent_messages', 'output_tokens')
    op.drop_column('agent_messages', 'input_tokens')
    op.drop_column('agent_messages', 'parent_message_id')
    # ### end Alembic commands ###
